pipeline {
    agent any

    stages {
        // Build Stage
        stage('Build') {
            steps {
                echo 'Building the application...'
            }
            post {
                always {
                    // Send build info to Jira, associating it with the SCRUM-1 issue
                    jiraSendBuildInfo site: 'fossops.atlassian.net', branch: 'SCRUM-1'
                }
            }
        }

        // Deployment Stage: Staging
        stage('Deploy to Staging') {
            when {
                branch 'main'  // Trigger only on the main branch
            }
            steps {
                echo 'Deploying to Staging...'
            }
            post {
                always {
                    // Send deployment info for the Staging environment
                    jiraSendDeploymentInfo environmentId: 'stg-env-1', environmentName: 'staging', environmentType: 'staging', issueKeys: ['SCRUM-1'], state: 'successful'
                }
            }
        }

        // Deployment Stage: Production
        stage('Deploy to Production') {
            when {
                branch 'main'
            }
            steps {
                echo 'Deploying to Production...'
            }
            post {
                always {
                    // Send deployment info for the Production environment
                    jiraSendDeploymentInfo environmentId: 'prod-env-1', environmentName: 'production', environmentType: 'production', issueKeys: ['SCRUM-1'], state: 'successful'
                }
            }
        }
    }
}
