pipeline:
  identifier: default
  name: default
  orgIdentifier: default
  projectIdentifier: default
  properties:
    ci:
      codebase:
        build: <+input>
  stages:
  - stage:
      identifier: build
      name: build
      spec:
        cloneCodebase: true
        execution:
          steps:
          - stepGroup:
              identifier: Stage__null52dfeb
              name: Checkout
              timeout: ""
          - stepGroup:
              identifier: Stage__null448305
              name: Build
              steps:
              - step:
                  identifier: sh9be189
                  name: sh
                  spec:
                    command: ./gradlew clean test
                    image: alpine
                    shell: Sh
                  timeout: ""
                  type: Run
              timeout: ""
          - stepGroup:
              identifier: Stage__nulle7d4a6
              name: Report
              steps:
              - step:
                  identifier: allure3c2e01
                  name: allure
                  spec:
                    image: harnesscommunity/allure:jdk21
                    command: allure generate build/allure-results --clean --output allure-report
                    shell: Sh
                  timeout: ""
                  type: Run
              - step:
                  identifier: uploadpublish3c2e01
                  name: Upload and Publish
                  spec:
                    image: harnesscommunity/drone-s3-upload-publish
                    settings:
                      artifact_file: artifact.txt
                      aws_access_key_id: <+input>
                      aws_bucket: <+input>
                      aws_secret_access_key: <+input>
                      source: allure-report
                      target: <+pipeline.sequenceId>
                  timeout: ""
                  type: Plugin
              timeout: ""
        platform:
          arch: Amd64
          os: Linux
        runtime:
          spec: {}
          type: Cloud
      type: CI
